<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var \frontend\models\SignupForm $model */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Home';
?>

<div class="site-index">
    <!-- Hero Section -->
    <div class="jumbotron text-center bg-white">
        <h1 class="display-4"><i class="fas fa-graduation-cap text-primary"></i> IELTS Practice Platform</h1>
        <p class="lead">Prepare for your IELTS exam with AI-generated practice tests</p>
        <p class="lead">Master Listening and Reading sections with realistic test scenarios</p>
        <hr class="my-4">
        <p>Join thousands of students improving their IELTS scores</p>
        <p>
            <a class="btn btn-primary btn-lg mr-2" href="<?= Url::to(['/site/signup']) ?>" role="button">
                <i class="fas fa-user-plus"></i> Get Started Free
            </a>
            <a class="btn btn-outline-primary btn-lg" href="<?= Url::to(['/site/login']) ?>" role="button">
                <i class="fas fa-sign-in-alt"></i> Login
            </a>
        </p>
    </div>

    <!-- Features Section -->
    <div class="row mt-5">
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-robot fa-4x text-primary mb-3"></i>
                    <h5 class="card-title">AI-Generated Tests</h5>
                    <p class="card-text">Unlimited practice tests generated by advanced AI, tailored to your level</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-headphones fa-4x text-success mb-3"></i>
                    <h5 class="card-title">Realistic Listening Tests</h5>
                    <p class="card-text">Practice with authentic audio recordings in various accents and scenarios</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-chart-line fa-4x text-info mb-3"></i>
                    <h5 class="card-title">Track Your Progress</h5>
                    <p class="card-text">Monitor your improvement with detailed analytics and performance insights</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Statistics Section -->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="text-center mb-4">Why Choose Us?</h2>
        </div>
        <div class="col-md-3 text-center">
            <h1 class="text-primary"><i class="fas fa-users"></i></h1>
            <h3>1000+</h3>
            <p>Active Students</p>
        </div>
        <div class="col-md-3 text-center">
            <h1 class="text-success"><i class="fas fa-file-alt"></i></h1>
            <h3>500+</h3>
            <p>Practice Tests</p>
        </div>
        <div class="col-md-3 text-center">
            <h1 class="text-warning"><i class="fas fa-star"></i></h1>
            <h3>7.5+</h3>
            <p>Average Score</p>
        </div>
        <div class="col-md-3 text-center">
            <h1 class="text-info"><i class="fas fa-clock"></i></h1>
            <h3>24/7</h3>
            <p>Access</p>
        </div>
    </div>

    <!-- How It Works Section -->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="text-center mb-4">How It Works</h2>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <div class="badge badge-primary mb-3" style="font-size: 24px; width: 50px; height: 50px; line-height: 35px; border-radius: 50%;">1</div>
                    <h5>Sign Up</h5>
                    <p>Create your free account in seconds</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <div class="badge badge-success mb-3" style="font-size: 24px; width: 50px; height: 50px; line-height: 35px; border-radius: 50%;">2</div>
                    <h5>Choose Test</h5>
                    <p>Select from Listening or Reading tests</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <div class="badge badge-info mb-3" style="font-size: 24px; width: 50px; height: 50px; line-height: 35px; border-radius: 50%;">3</div>
                    <h5>Take Test</h5>
                    <p>Practice with realistic exam conditions</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <div class="badge badge-warning mb-3" style="font-size: 24px; width: 50px; height: 50px; line-height: 35px; border-radius: 50%;">4</div>
                    <h5>Get Results</h5>
                    <p>Receive instant feedback and band score</p>
                </div>
            </div>
        </div>
    </div>

    <!-- CTA Section -->
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <div class="card bg-primary text-white text-center">
                <div class="card-body p-5">
                    <h2>Ready to Start Your IELTS Journey?</h2>
                    <p class="lead">Join our platform today and ace your IELTS exam!</p>
                    <a href="<?= Url::to(['/site/signup']) ?>" class="btn btn-light btn-lg">
                        <i class="fas fa-rocket"></i> Start Practicing Now
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
